オプションページの追加
twin-te/manaba-report-integration pull request #51
Opened 2022-12-12 13:46 UTC by onokatio

サービスの選択・ログインを行う項目をポップアップから抜き出してオプションページに分離しました。
自分のAPIキーにて正常に同期できることを確認しています。

<img width="1792" alt="スクリーンショット 2022-12-12 21 57 51" src="https://user-images.githubusercontent.com/14256420/207059365-36cdd2fa-e3d7-451c-9202-7286aea4c944.png">
<img width="480" alt="スクリーンショット 2022-12-12 22 29 37" src="https://user-images.githubusercontent.com/14256420/207059373-7a37279b-592a-498e-bbca-e19a55182fa4.png">

close #23

2022-12-12 13:53 UTC, onokatio commented
@HosokawaR @azarashi2931 確認お願いします。

2022-12-15 17:42 UTC, HosokawaR requested changes
ありがとうございます。おまたせしてすみません。

厄介なバグだったので、整備してもらい助かりました！
またオプションページのデザインも Simple is Best という感じで素敵です！

いくつかコメントさせてもらったので確認してもらえると嬉しいです。

2022-12-15 17:42 UTC, HosokawaR commented on public/options.html
> +    <title>Document</title>
```suggestion
    <title>設定 | Manaba Report Integration by Twin:te</title>
```
細かい話なのですが、ユーザに見える部分ですのでしっかりしたページの名前をつけてあげたいです！
![image](https://user-images.githubusercontent.com/45098934/207926284-38f16257-6929-4c3d-9be8-88feba91644c.png)

2022-12-15 17:42 UTC, HosokawaR commented on public/manifest.json
> +    "https://trello.com/"
```suggestion
    "https://github.com/"
```
`https://trello.com/` はなくても動くと思ったのですが、いかがでしょうか。（少なくともこちらの手元では動作しました。）

`https://github.com/` のみ指定されている理由は以下に記載されております。
https://github.com/twin-te/manaba-report-integration/pull/28

2022-12-15 17:42 UTC, HosokawaR commented on src/options/main.tsx
> +//import styled from 'styled-components'
```suggestion
```

コピペ等でもとからあった場合は恐縮ですが、余分なコメントはけしていただけると幸いです！

2022-12-15 17:42 UTC, HosokawaR commented on src/popup/main.tsx
> +//import RepositoryItem from '../options/repositoryItem'
```suggestion
```

2022-12-15 17:47 UTC, HosokawaR commented
MEMO
 
![image](https://user-images.githubusercontent.com/45098934/207931091-5fa5fe01-b988-4306-9a54-a7fc11913249.png)
初めてこの拡張機能を起動する場合は「同期」がグレーアウトしており、設定ページ（オプションページ）の存在を知らなくとも、ユーザはある程度自然な流れで設定ページに推移してくれると思われる。

2022-12-16 03:11 UTC, HosokawaR approved these changes
対応していただきありがとうございます！

Merge 後、すぐに拡張機能の更新申請をします。

2022-12-16 04:02 UTC, merged

2022-12-16 05:55 UTC, onokatio commented
@HosokawaR すみません、まだ途中でした...!（権限からtrello.comを消していない）

2022-12-16 05:55 UTC, onokatio commented
特段問題ではないので別にPR出します。

2022-12-16 05:59 UTC, HosokawaR commented
すみません、早とちりしてしまいました。
ありがとうございます。